name: Docker Build Images

concurrency:
    group: build-docker-${{ github.ref }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Keycloak version'
                required: true
                type: string
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        timeout-minutes: 16
        steps:
            - uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              with:
                  version: v0.9.1
            -   name: Login to docker ghcr.io registry
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: USERNAME
                    password: ${{ secrets.GHCR_TOKEN }}
            -
                name: Docker keycloak  meta
                id: keycloak
                uses: docker/metadata-action@v4
                with:
                    images: |
                        ghcr.io/daniel-marynicz/keycloak
            -   name: test
                env:
                    VERSION: "${{ inputs.version }}"
                    TAG: "ghcr.io/daniel-marynicz/keycloak:${{ inputs.version }}"
                run: |
                    cat "${{ steps.keycloak.outputs.bake-file }}"
                    docker buildx bake  -f docker-bake.hcl -f "${{ steps.keycloak.outputs.bake-file }}" --print
            -   name: Bake keycloak and push
                uses: docker/bake-action@v2
                if: ${{ github.event_name != 'pull_request' }}
                env:
                    VERSION: "${{ inputs.version }}"
                    TAG: "ghcr.io/daniel-marynicz/keycloak:${{ inputs.version }}"
                with:
                    files: |
                        ./docker-bake.hcl
                        ${{ steps.keycloak.outputs.bake-file }}
                    push: false
